import Head from "next/head";
import * as React from "react";
import Button from "@mui/material/Button";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">Loginnn :) </div>
        <Button variant="contained">Hello World</Button>
      </main>
    </>
  );
}
